const Leaders = [
  { id: 1, leaderName: "Bashar", power: 2, faction: "E" },
  { id: 2, leaderName: "Burseg", power: 3, faction: "E" },
  { id: 3, leaderName: "Caid", power: 3, faction: "E" },
  { id: 4, leaderName: "Captain Aramsham", power: 5, faction: "E" },
  { id: 5, leaderName: "Hasimir Fenring", power: 6, faction: "E" },
  { id: 6, leaderName: "Guild Representative", power: 1, faction: "SG" },
  { id: 7, leaderName: "Soo-Soo Sook", power: 2, faction: "SG" },
  { id: 8, leaderName: "Esmar Tuek", power: 3, faction: "SG" },
  { id: 9, leaderName: "Master Bewt", power: 3, faction: "SG" },
  { id: 10, leaderName: "Staban Tuek", power: 5, faction: "SG" },
  { id: 11, leaderName: "Jamis", power: 2, faction: "FM" },
  { id: 12, leaderName: "Shadout Mapes", power: 3, faction: "FM" },
  { id: 13, leaderName: "Otheym", power: 5, faction: "FM" },
  { id: 14, leaderName: "Chani", power: 6, faction: "FM" },
  { id: 15, leaderName: "Stilgar", power: 7, faction: "FM" },
  { id: 16, leaderName: "Dr. Wellington Yueh", power: 1, faction: "A" },
  { id: 17, leaderName: "Duncan Idaho", power: 2, faction: "A" },
  { id: 18, leaderName: "Gurney Halleck", power: 4, faction: "A" },
  { id: 19, leaderName: "Thufir Hawat", power: 5, faction: "A" },
  { id: 20, leaderName: "Lady Jessica", power: 5, faction: "A" },
  { id: 21, leaderName: "Alia", power: 5, faction: "BG" },
  { id: 22, leaderName: "Wanna Marcus", power: 5, faction: "BG" },
  { id: 23, leaderName: "Princess Irulan", power: 5, faction: "BG" },
  { id: 24, leaderName: "Nargot Lady Fenring", power: 5, faction: "BG" },
  { id: 25, leaderName: "Mother Ramallo", power: 5, faction: "BG" },
  { id: 26, leaderName: "Umman Kudu", power: 1, faction: "H" },
  { id: 27, leaderName: "Captain Iakin Nefud", power: 2, faction: "H" },
  { id: 28, leaderName: "Piter de Vries", power: 3, faction: "H" },
  { id: 29, leaderName: "Beast Rabban", power: 4, faction: "H" },
  { id: 30, leaderName: "Feyd Rautha", power: 6, faction: "H" }
];

export default Leaders;
